### ISSUE TITLE
Error: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by antonlovric** [cody-greene/node-rabbitmq-client#27]
Hey everyone, I have a RabbitMQ broker running in the background and a .NET Core backend publishing messages. I need to connect to the broker inside my React app I created using Vite. This is the code I use for connecting to the broker:

```tsx
import { Connection } from 'rabbitmq-client';

  useEffect(() => {
    const rabbit = new Connection("amqp://guest:guest@localhost:5672");

    rabbit.on('connection', () => {
      console.log('connected');
    });
    rabbit.on('error', () => {
      console.log('error');
    });

    return () => {
      rabbit.close();
    };
  }, []);
```

But I get this error when the code snippet is called:

```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node_modules/rabbitmq-client/lib/util.js (util.js:106:43)
    at __require2 (chunk-WQG2LZMB.js?v=fa4e550a:16:50)
    at node_modules/rabbitmq-client/lib/Connection.js (Connection.js:11:16)
    at __require2 (chunk-WQG2LZMB.js?v=fa4e550a:16:50)
    at node_modules/rabbitmq-client/lib/index.js (index.js:4:22)
    at __require2 (chunk-WQG2LZMB.js?v=fa4e550a:16:50)
    at index.js:12:126
```

Any idea what I'm doing wrong or what I can do to resolve this issue?

Side note, this warning also shows up in the browser console:

```
Module "node:stream" has been externalized for browser compatibility. Cannot access "node:stream.Writable" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

**Comment by cody-greene** [comment]
This library does not work in the browser. Perhaps I'll add support in the future. But not any time soon.

-------- Original Message --------

**Comment by cody-greene** [comment]
I believe cloudamqp maintains a library which uses web sockets.

-------- Original Message --------

**Comment by antonlovric** [comment]
Thanks!
