### ISSUE TITLE
Invalid FRAME_END octet

### ISSUE THREAD

**Issue by T1MOXA** [cody-greene/node-rabbitmq-client#63]
runtime: bun.js: 1.1.12
rabbitmq-client: 5.0.0 and 4.6.0
rabbitmqctl version: 3.12.2

 ```
AMQPConnectionError: invalid FRAME_END octet: 208
  code: "FRAME_ERROR"

       at new AMQPError (/workspace/node_modules/rabbitmq-client/lib/exception.js:9:13)
       at new AMQPChannelError (:1:28)
       at new AMQPConnectionError (:1:28)
       at /workspace/node_modules/rabbitmq-client/lib/codec.js:606:40
```

* values seems random 0,1,60,101,116, 208, etc...

**Comment by cody-greene** [comment]
Please include sample code so I can reproduce this.

-------- Original Message --------

**Comment by T1MOXA** [comment]
For now I didn't find a way to reproduce. Error ocurs occasionaly.

**Comment by cressie176** [comment]
It's most likely https://github.com/oven-sh/bun/issues/5627. Bun is not even close to production ready.

**Comment by cody-greene** [comment]
Yes this is definitely due to bun's different behavior (intentional or not, who knows?) with the Buffer or Streams API. If you have large messages then, as a temporary solution, you can try increasing the `frameMax` connection option to prevent the message body from being split into multiple chunks, hopefully avoiding whatever causes this error.

**Comment by cody-greene** [comment]
Yep, Bun v1.2.3 has a bug/divergence on `Buffer.writeBigUInt64BE()`

https://nodejs.org/api/buffer.html#bufwritebiguint64bevalue-offset
> buf.writeBigUInt64BE(value[, offset])
> - value [<bigint>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) Number to be written to buf.
> - offset [<integer>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type) Number of bytes to skip before starting to write. Must satisfy: 0 <= offset <= buf.length - 8. Default: 0.
> - **Returns: [<integer>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type) offset plus the number of bytes written.**
>
> Writes value to buf at the specified offset as big-endian.

However in bun v1.2.3, this method returns only the offset, e.g.
```javascript
const buf = Buffer.alloc(8)
buf.writeBigUInt64BE(7n, 0) // returns 8 (node) or 0 (bun)
```

This is causing my frame encoder to produce nonsense because I use the returned offset in subsequent buffer writes. I'll fix it soon(?).

**Comment by deeprisk-ajohn** [comment]
Looks like that bug was resolved in 1.2.4 👍 
https://bun.sh/blog/bun-v1.2.4#buffer-fixes
