### ISSUE TITLE
Cannot find module 'node:net' happened 

### ISSUE THREAD

**Issue by newwayxp** [cody-greene/node-rabbitmq-client#7]
I used a simple js like below
`const Connection =require('rabbitmq-client') `
but exception happened.
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:net'
Require stack:
- /Users/keyin/code/framwork/node_modules/.pnpm/rabbitmq-client@3.3.0/node_modules/rabbitmq-client/lib/Connection.js
- /Users/keyin/code/framwork/node_modules/.pnpm/rabbitmq-client@3.3.0/node_modules/rabbitmq-client/lib/index.js
- /Users/keyin/code/framwork/sample.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/keyin/code/framwork/node_modules/.pnpm/rabbitmq-client@3.3.0/node_modules/rabbitmq-client/lib/Connection.js:29:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/keyin/code/framwork/node_modules/.pnpm/rabbitmq-client@3.3.0/node_modules/rabbitmq-client/lib/Connection.js',
    '/Users/keyin/code/framwork/node_modules/.pnpm/rabbitmq-client@3.3.0/node_modules/rabbitmq-client/lib/index.js',
    '/Users/keyin/code/framwork/sample.js'
  ]
}

**Comment by newwayxp** [comment]
my node version is v14.16.1.

**Comment by cody-greene** [comment]
Support for "node:" prefixed imports was added in [node v14.18](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V14.md#2021-09-28-version-14180-fermium-lts-targos).

Can you upgrade to at least node-v14.18?

I test this library for v14.x v16.x and v18.x, but only the most recent patch for each branch. Also 14.x will soon be end-of-life (2023-04-30, https://nodejs.dev/en/about/releases/)
